#!/usr/bin/env python3
"""Generate the two shape-outside polygons that confine text to a circle.

The popup is a circle of radius R in a 2R x 2R box. Two floats — each R wide
and 2R tall — carry a polygon describing the part of their half-box that lies
OUTSIDE the circle, so every line box is clipped to the circle's chord at its
own height.

Values are percentages of each float's own box, which makes them scale-free:
the same two rules work for every popup radius. Regenerate with a smaller
--step for a finer arc (the default samples every 2.5% of height, ~10px at
R=210 — comfortably finer than a line box).

    python3 tools/circle-shape.py > src/lib/circle-shape.css
"""
import argparse
import math


def x_left(t):
    """Left edge of the circle at height t (0-100), as a % of the half-box."""
    u = t / 50.0 - 1.0
    return 100.0 * (1.0 - math.sqrt(max(0.0, 1.0 - u * u)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--step", type=float, default=2.5,
                    help="arc sample interval, in %% of height (default 2.5)")
    ap.add_argument("--margin", default="1em",
                    help="shape-margin: the inset from the circle's edge")
    args = ap.parse_args()

    ts = [i * args.step for i in range(int(100 / args.step) + 1)]
    fmt = lambda pts: ", ".join("%g%% %g%%" % (x, y) for x, y in pts)

    # Left float: the arc, then down the left edge and back up.
    left = fmt([(round(x_left(t), 2), t) for t in ts] + [(0, 100), (0, 0)])
    # Right float: the mirrored arc, then out to the right edge.
    right = fmt([(round(100 - x_left(t), 2), t) for t in ts]
                + [(0, 100), (100, 100), (100, 0)])

    print("/* Generated by tools/circle-shape.py — do not hand-edit. */")
    print(".popup-exclude-left,")
    print(".popup-exclude-right { width: 50%%; height: 100%%; shape-margin: %s; }" % args.margin)
    print(".popup-exclude-left  { float: left;  shape-outside: polygon(%s); }" % left)
    print(".popup-exclude-right { float: right; shape-outside: polygon(%s); }" % right)


if __name__ == "__main__":
    main()
